version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage

  app:
    build: .
    depends_on:
      - qdrant
    volumes:
      - ./my_docs:/app/my_docs
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
    stdin_open: true
    tty: true

volumes:
  qdrant_storage:
